### ISSUE TITLE
Build failures due to missing source files

### ISSUE THREAD

**Issue by AkarinVS** [AmusementClub/vcm#1]
The current mod builds fails with missing source files:
`ConvertBGRforInput.h` and `spotlightDim.h`.

The last working build is at tag [2021-09-14.AC](https://github.com/AmusementClub/vcm/tree/2021-09-14.AC)

**Comment by theChaosCoder** [comment]
vcmohan added the missing files. Repo was updated too.

**Comment by NSQY** [comment]
> vcmohan added the missing files. Repo was updated too.

Circles.cpp seems to be missing still.


../vcm.cpp:82:10: fatal error: Circles.cpp: No such file or directory
   82 | #include "Circles.cpp"
      |          ^~~~~~~~~~~~~

**Comment by theChaosCoder** [comment]
Try again (fingers crossed)

**Comment by AkarinVS** [comment]
After merging the "Add missing files - Part 2" commit, here are some remaining build errors:

- Circles.cpp: missing definition of BGR8_YUV (this is the sole usage of the identifier)
- Fisheye.cpp, FisheyePart.cpp, moveDeBarrel.cpp: missing definitions of setInterpolationScheme and bestOfNineIndex
- FourFoldSymmetricMarking.h: calls to LaQuantile provides 7 arguments, the only known implementation in interpolationMethods.h only requires 6.
- Missing definition for f2qsharpCreate, f2qsharpCreate, and f2qcorrCreate. (likely missing source file?)

**Comment by theChaosCoder** [comment]
Small error on my part. I replaced all files but have not checked for deleted files.

**Comment by JustinTArthur** [comment]
@theChaosCoder after cherry-picking your file deletion commit, the missing definitions that @AkarinVS mentioned are still a problem.

**Comment by theChaosCoder** [comment]
Well somehow the author is able to compile it: https://forum.doom9.org/showthread.php?p=1961281#post1961281

**Comment by theChaosCoder** [comment]
We got multiple updates again, I'm 99% sure it is the final version now.

**Comment by AkarinVS** [comment]
Unfortunately, it still doesn't build....

LaQuantile function defined in
https://github.com/Vapoursynth-Plugins-Gitify/vcm/blob/3c99e8736092d8dea440114d8e8b3f66562bb9d2/interpolationMethods.h#L56
requires 7 parameters,
but some callers only pass 6 arguments:
https://github.com/Vapoursynth-Plugins-Gitify/vcm/blob/3c99e8736092d8dea440114d8e8b3f66562bb9d2/FisheyePart.cpp#L331

https://github.com/Vapoursynth-Plugins-Gitify/vcm/blob/3c99e8736092d8dea440114d8e8b3f66562bb9d2/vcm.cpp#L137
references undefined function f2qblurCreate.

**Comment by theChaosCoder** [comment]
New update with new relelease. Both points seems to be adressed.
